### ISSUE TITLE
Cannot read properties of undefined (reading 'email')

### ISSUE THREAD

**Issue by markelog** [jsayol/vscode-firebase-explorer#36]
Hi there, see this in the logs.
```
[2022-10-31 14:00:31.918] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'email')
    at /Users/markelog/.vscode/extensions/jsayol.firebase-explorer-0.3.3/dist/extension.js:241:23497
    at Array.filter (<anonymous>)
    at Function.addAccount (/Users/markelog/.vscode/extensions/jsayol.firebase-explorer-0.3.3/dist/extension.js:241:23480)
    at X (/Users/markelog/.vscode/extensions/jsayol.firebase-explorer-0.3.3/dist/extension.js:241:26958)
    at n._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:111316) firebaseExplorer.accounts.add {"value":"jsayol.firebase-explorer","_lower":"jsayol.firebase-explorer"}
```

I am authenticated via `firebase` and `gcloud`. Am I missing something?

**Comment by Dan1ell** [comment]
Having the same problem: Cannot read properties of undefined (reading 'email').

**Comment by ysb73** [comment]
The same problem: Cannot read properties of undefined (reading 'email').
